name: "Binary Release"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    uses: jenpet/giks/.github/workflows/test-build.yml@master
    with:
      upload_artifacts: true
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Extract Version
        id: extract_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: giks-dist-${{steps.extract_version.outputs.VERSION}}
          path: build/dist/
      - name: GitHub Release
        id: github_release
        run: |
          set -x
          assets=()
          for asset in ./build/dist/; do
            assets+=("-a" "${asset}")
          done
          hub release create $(find ./build/dist -type f -name "giks_*" -printf "-a %p ") -m "${{steps.extract_version.outputs.VERSION}}" -m "giks release ${{steps.extract_version.outputs.VERSION}}" "${{steps.extract_version.outputs.VERSION}}"
        env:
          GITHUB_TOKEN: ${{ github.token }}